Repository Smooth-2025/mobile-frontend, pull requests merged in 2025-09, with the labels that each got.

#103 PR: US10.6 - 119 신고 모달 → dev 머지
  src/components/emergency/EmergencyCallAlert.styles.ts
  src/components/emergency/EmergencyCallAlert.tsx
  src/components/emergency/EmergencyReportedAlert.tsx
  src/hooks/useEmergencyHandler.ts
Labels: Feature

#105 PR: T10.10.3 - axiosBaseQuery 오류 수정 → US10.10 머지
  src/apis/axiosBaseQuery.ts
Labels: bug

#106 PR: US10.16 - 웹소켓 주행 성향 → dev 머지
  src/components/driving/DrivingSimulation.tsx
  src/components/driving/dumiData.ts
  src/store/websocket/types.ts
  src/store/websocket/websocketMiddleware.ts
Labels: Feature

#110 PR: T10.10.3 - 컴포넌트 폴더명수정 → US10.10 머지
  src/apis/temp.tsx
  src/components/history/DrivingCard.styles.ts
  src/components/history/DrivingCard.tsx
  src/components/history/DrivingHistory.styles.ts
  src/components/history/DrivingHistory.tsx
  src/components/history/ReportCard.styles.ts
  src/components/history/ReportCard.tsx
  src/components/history/StampBoard.styles.ts
  src/components/history/StampBoard.tsx
  src/components/portal/BottomSheetPortal.styles.ts
  src/components/portal/BottomSheetPortal.tsx
  src/components/portal/DrivePortal.tsx
  src/components/simulation/DrivingLane.tsx
  src/components/simulation/DrivingSimulation.styles.ts
  src/components/simulation/DrivingSimulation.tsx
  src/components/simulation/SimulationCar.tsx
  src/components/simulation/SimulationGround.tsx
  src/components/simulation/dumiData.ts
  src/components/simulation/useDumiPlayback.ts
  src/components/summary/CharacterTraits.styles.ts
  src/components/summary/CharacterTraits.tsx
  src/components/summary/TodaySummary.styles.ts
  src/components/summary/TodaySummary.tsx
  src/components/summary/WeeklySummary.styles.ts
  src/components/summary/WeeklySummary.tsx
  src/components/vehicle/VehicleLinkForm.styles.ts
  src/components/vehicle/VehicleLinkForm.tsx
  src/components/vehicle/VehicleLinkSheet.styles.ts
  src/components/vehicle/VehicleLinkSheet.tsx
  src/components/vehicle/VehicleLinkedView.styles.ts
  src/components/vehicle/VehicleLinkedView.tsx
  src/components/vehicle/VehicleUnlinkedView.styles.ts
  src/components/vehicle/VehicleUnlinkedView.tsx
  src/constants/temp.ts
  src/layout/AppLayout.tsx
  src/pages/drive/DrivePage.tsx
  src/pages/driveOverlay/DriveOverlayPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/myPage/ProfilePage.tsx
  src/pages/report/ReportPage.tsx
Labels: Task

#119 PR: refactor-US10.16 - 웹소켓 로직 리팩토링 → US10.16 머지
  src/store/websocket/websocketMiddleware.ts
Labels: Feature

#125 PR: US10.4 - 알림 수신 반응API로직 구현 → dev 머지
  src/apis/alertsApi.ts.ts
  src/pages/driveOverlay/DriveOverlayPage.tsx
Labels: Feature

#126 refactor-US10.16 - 웹소켓 로직 리팩토링 → US10.16 머지
  src/layout/AppLayout.tsx
  src/store/slices/alertSlice.ts
  src/store/slices/drivingSlice.ts
  src/store/websocket/websocketMiddleware.ts
Labels: Feature

#128 PR: T10.10.3 -주행현환조회 API 로직 변경 → US10.10 머지
  src/components/history/StampBoard.tsx
  src/store/report/reportApi.ts
  src/store/report/type.ts
Labels: Task

#136 PR: refactor-US10.16 - 웹소켓 로직 리팩토링(토큰) → US10.16 머지
  src/apis/alertsApi.ts
  src/apis/drivecast.ts
  src/apis/emergency.ts
  src/hooks/useEmergencyHandler.ts
  src/store/websocket/websocketMiddleware.ts
Labels: Feature

#137 PR: feat-US10.16 - 웹소켓 로직 리팩토링(토큰) →dev 머지
  src/apis/alertsApi.ts
  src/apis/drivecast.ts
  src/apis/emergency.ts
  src/hooks/useEmergencyHandler.ts
  src/store/websocket/websocketMiddleware.ts
Labels: enhancement, Feature

#141 # PR: fix-dev- 배포테스트 오류및 코드 수정 → dev 머지
  src/apis/axiosBaseQuery.ts
  src/components/common/Input/Input.styles.ts
  src/components/summary/CharacterTraits.tsx
  src/components/summary/TodaySummary.tsx
  src/components/summary/WeeklySummary.tsx
  src/pages/NotFoundPage.style.ts
  src/pages/NotFoundPage.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/myPage/ProfilePage.tsx
  src/store/baseApi.ts
  src/store/driving/drivingApi.ts
  src/store/index.ts
  src/store/report/reportApi.ts
  src/store/vehicle/vehicleApi.ts
  vercel.json
Labels: bug

#143 PR: US10.5- 도로 주행환경 개발 → dev 머지
  public/vite.svg
  src/components/simulation/DrivingSimulation.tsx
  src/components/simulation/ErrorBoundary.styles.ts
  src/components/simulation/ErrorBoundary.tsx
  src/components/simulation/ErrorDisplay.styles.ts
  src/components/simulation/ErrorDisplay.tsx
  src/components/simulation/ErrorHandling.ts
  src/components/simulation/FallbackRenderer.tsx
  src/components/simulation/GeometrySampler.ts
  src/components/simulation/LoadingIndicator.styles.ts
  src/components/simulation/LoadingIndicator.tsx
  src/components/simulation/OpenDriveVisualization.styles.ts
  src/components/simulation/OpenDriveVisualization.tsx
  src/components/simulation/RoadEnvironment.tsx
  src/components/simulation/SimulationCar.tsx
  src/components/simulation/VehicleManager.tsx
  src/components/simulation/XodrGround3D.styles.ts
  src/components/simulation/XodrGround3D.tsx
  src/components/simulation/XodrParser.ts
  src/components/simulation/types.ts
  src/components/simulation/utils/coordinateUtils.ts
  src/components/temp.tsx
  src/utils/laneBoundaryUtils.ts
  src/utils/temp.ts
Labels: Feature

#144 PR: US10.2 - 버그사항 수정 → dev 머지
  src/apis/index.ts
  src/layout/AppLayout.tsx
  src/store/slices/authSlice.ts
  src/store/vehicle/vehicleApi.ts
Labels: bug

#146 PR: dev - 1차 배포 이슈사항 수정 → main 머지
  public/vite.svg
  src/apis/axiosBaseQuery.ts
  src/apis/index.ts
  src/components/common/Input/Input.styles.ts
  src/components/history/DrivingCard.styles.ts
  src/components/history/DrivingCard.tsx
  src/components/history/DrivingHistory.styles.ts
  src/components/history/DrivingHistory.tsx
  src/components/history/ReportCard.styles.ts
  src/components/simulation/DrivingSimulation.tsx
  src/components/simulation/ErrorBoundary.styles.ts
  src/components/simulation/ErrorBoundary.tsx
  src/components/simulation/ErrorDisplay.styles.ts
  src/components/simulation/ErrorDisplay.tsx
  src/components/simulation/ErrorHandling.ts
  src/components/simulation/FallbackRenderer.tsx
  src/components/simulation/GeometrySampler.ts
  src/components/simulation/LoadingIndicator.styles.ts
  src/components/simulation/LoadingIndicator.tsx
  src/components/simulation/OpenDriveVisualization.styles.ts
  src/components/simulation/OpenDriveVisualization.tsx
  src/components/simulation/RoadEnvironment.tsx
  src/components/simulation/SimulationCar.tsx
  src/components/simulation/VehicleManager.tsx
  src/components/simulation/XodrGround3D.styles.ts
  src/components/simulation/XodrGround3D.tsx
  src/components/simulation/XodrParser.ts
  src/components/simulation/types.ts
  src/components/simulation/utils/coordinateUtils.ts
  src/components/summary/CharacterTraits.tsx
  src/components/summary/TodaySummary.tsx
  src/components/summary/WeeklySummary.tsx
  src/components/temp.tsx
  src/layout/AppLayout.tsx
  src/pages/NotFoundPage.style.ts
  src/pages/NotFoundPage.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/myPage/ProfilePage.tsx
  src/store/baseApi.ts
  src/store/driving/drivingApi.ts
  src/store/index.ts
  src/store/report/reportApi.ts
  src/store/slices/authSlice.ts
  src/store/vehicle/vehicleApi.ts
  src/utils/laneBoundaryUtils.ts
  src/utils/temp.ts
  vercel.json
Labels: bug

#147 PR: fix-dev - 스타일 이슈 수정→ dev 머지
  src/components/report/AccidentResponse.tsx
  src/components/report/DrivingBehavior.tsx
  src/components/report/DrivingDNA.tsx
  src/components/report/DrivingSummary.tsx
  src/utils/timeUtils.ts
Labels: bug

#148 PR: dev - 1차 배포 이슈사항 수정 → main 머지
  src/components/report/AccidentResponse.tsx
  src/components/report/DrivingBehavior.tsx
  src/components/report/DrivingDNA.tsx
  src/components/report/DrivingSummary.tsx
  src/utils/timeUtils.ts
Labels: bug

#149 PR: fix-main - 주행 요약카드 스타일 이슈 수정 → main
  src/components/history/DrivingCard.tsx
Labels: bug
